/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PromoBanner = {
	_type: 'promo-banner'
	promoTitle?: string
	promoDescription?: string
	promoCtas?: Array<
		{
			_key: string
		} & Cta
	>
	promoAdditionalText?: string
	promoFeatures?: Array<{
		text?: string
		_key: string
	}>
}

export type Crm2 = {
	_type: 'crm2'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	subcontent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	ctaTagline?: string
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	additionalInfo?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	secondPretitle?: string
	secondContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	secondSubcontent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	secondThirdContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	secondImage?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	thirdPretitle?: string
	thirdContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	thirdSubcontent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	thirdThirdContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	thirdImage?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	fourthPretitle?: string
	fourthContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	fourthSubcontent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	fourthThirdContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	fourthImage?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	fifthPretitle?: string
	fifthContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	fifthSubcontent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	fifthThirdContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	fifthImage?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	featuresPretitle?: string
	featuresContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	features?: Array<{
		icon?: {
			asset?: {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
			}
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			alt?: string
			_type: 'image'
		}
		title?: string
		description?: string
		_key: string
	}>
	integrationPretitle?: string
	integrationContent?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	integrationSubtitle?: string
	integrationModules?: Array<{
		englishTitle?: string
		arabicTitle?: string
		description?: string
		icon?: {
			asset?: {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
			}
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		_key: string
	}>
}

export type JobApplicationTabs = {
	_type: 'jobApplicationTabs'
	title?: string
	subtitle?: string
	tabs?: Array<{
		label?: string
		sublabel?: string
		type?: 'form' | 'text'
		mainTitle?: string
		subtitle?: string
		introText?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		description?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		requirements?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		benefits?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		button?: {
			text?: string
			link?: string
		}
		seats?: number
		addedDate?: string
		_key: string
	}>
	headerImages?: Array<{
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
		_key: string
	}>
}

export type ProductList = {
	_type: 'product-list'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	links?: Array<
		{
			_key: string
		} & Link
	>
	products?: Array<{
		productTitle?: string
		productDescription?: string
		productImage?: {
			asset?: {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
			}
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		link?: Link
		_type: 'product'
		_key: string
	}>
}

export type Features02 = {
	_type: 'features-02'
	benefits?: Array<{
		pretitle?: string
		content?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		image?: {
			asset?: {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
			}
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			alt?: string
			_type: 'image'
		}
		_key: string
	}>
}

export type Features01 = {
	_type: 'features-01'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	features?: Array<{
		features?: Array<{
			icon?: Icon
			image?: {
				asset?: {
					_ref: string
					_type: 'reference'
					_weak?: boolean
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
				}
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				loading?: 'lazy' | 'eager'
				_type: 'image'
			}
			title?: string
			description?: string
			_type: 'feature'
			_key: string
		}>
		_type: 'grid'
		_key: string
	}>
}

export type List02 = {
	_type: 'list-02'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	features?: Array<{
		icon?: Icon
		title?: string
		description?: string
		_key: string
	}>
}

export type HowItWorks = {
	_type: 'how-it-works'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	steps?: Array<{
		image?: {
			asset?: {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
			}
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		title?: string
		description?: string
		_key: string
	}>
}

export type Testimonials01 = {
	_type: 'testimonials-01'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	testimonials?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'testimonial'
	}>
}

export type Testimonials02 = {
	_type: 'testimonials-02'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	testimonials?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'testimonial'
	}>
}

export type Steps = {
	_type: 'steps'
	mainTitle?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	content1?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	content2?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	content3?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	image1?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	image2?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	image3?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
}

export type CallToAction02 = {
	_type: 'call-to-action-02'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	checkedList?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		onRight?: boolean
		loading?: 'lazy' | 'eager'
		_type: 'image'
	}
	textAlign?: 'left' | 'center' | 'right'
	alignItems?: 'start' | 'center' | 'end'
	bgImage?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		loading?: 'lazy' | 'eager'
		_type: 'image'
	}
	bgImageMobile?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
}

export type CallToAction01 = {
	_type: 'call-to-action-01'
	callToActionDoc?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'call.to.action.doc'
	}>
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		onRight?: boolean
		loading?: 'lazy' | 'eager'
		_type: 'image'
	}
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	checkedList?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
}

export type StatList = {
	_type: 'stat-list'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	stats?: Array<{
		value?: string
		text?: string
		_key: string
	}>
}

export type Testimonials03 = {
	_type: 'testimonials-03'
	logoImage?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	testimony?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	client?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	position?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	textAlign?: 'left' | 'center' | 'right'
	alignItems?: 'start' | 'center' | 'end'
}

export type RichtextModule = {
	_type: 'richtext-module'
	content?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: {
					_ref: string
					_type: 'reference'
					_weak?: boolean
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
				}
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				caption?: string
				_type: 'image'
				_key: string
		  }
	>
	contents?: boolean
}

export type PricingComparison = {
	_type: 'pricing-comparison'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	details?: Array<{
		title?: string
		specs?: Table
		_type: 'apps'
		_key: string
	}>
}

export type PricingCalculator = {
	_type: 'pricing-calculator'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	details?: Array<{
		title?: string
		specs?: Table
		_type: 'apps'
		_key: string
	}>
}

export type PricingList = {
	_type: 'pricing-list'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	plans?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'pricing'
	}>
}

export type Logos02 = {
	_type: 'logos-02'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	logoType?: 'default' | 'light' | 'dark'
	logos?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'logo'
	}>
}

export type Logos01 = {
	_type: 'logos-01'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	logos?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'logo'
	}>
}

export type Hero04 = {
	_type: 'hero-04'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		onRight?: boolean
		loading?: 'lazy' | 'eager'
		_type: 'image'
	}
}

export type Hero02 = {
	_type: 'hero-02'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
}

export type Hero01 = {
	_type: 'hero-01'
	pretitle?: {
		label?: string
		href?: string
	}
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
}

export type Hero03 = {
	_type: 'hero-03'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		onRight?: boolean
		loading?: 'lazy' | 'eager'
		_type: 'image'
	}
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
}

export type FaqList = {
	_type: 'faq-list'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	items?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'faq'
	}>
	sideNote?: {
		title?: string
		subtitle?: string
		link?: Link
	}
}

export type CustomHtml = {
	_type: 'custom-html'
	html?: string
}

export type CreativeModule = {
	_type: 'creative-module'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	modules?: Array<{
		subModules?: Array<
			| {
					ctas?: Array<
						{
							_key: string
						} & Cta
					>
					_type: 'ctas'
					_key: string
			  }
			| {
					icon?: {
						asset?: {
							_ref: string
							_type: 'reference'
							_weak?: boolean
							[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
						}
						media?: unknown
						hotspot?: SanityImageHotspot
						crop?: SanityImageCrop
						_type: 'image'
					}
					height?: number
					_type: 'icon'
					_key: string
			  }
			| {
					asset?: {
						_ref: string
						_type: 'reference'
						_weak?: boolean
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
					}
					media?: unknown
					hotspot?: SanityImageHotspot
					crop?: SanityImageCrop
					alt?: string
					aspectRatio?: string
					_type: 'image'
					_key: string
			  }
			| {
					content?: Array<{
						children?: Array<{
							marks?: Array<string>
							text?: string
							_type: 'span'
							_key: string
						}>
						style?:
							| 'normal'
							| 'h1'
							| 'h2'
							| 'h3'
							| 'h4'
							| 'h5'
							| 'h6'
							| 'blockquote'
						listItem?: 'bullet' | 'number'
						markDefs?: Array<{
							href?: string
							_type: 'link'
							_key: string
						}>
						level?: number
						_type: 'block'
						_key: string
					}>
					_type: 'richtext'
					_key: string
			  }
			| ({
					_key: string
			  } & CustomHtml)
		>
		colSpan?: number
		_key: string
	}>
	columns?: number
	textAlign?: 'left' | 'center' | 'right'
	alignItems?: 'start' | 'center' | 'end'
}

export type ContactUs = {
	_type: 'contact-us'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	title?: string
	contactInfo?: Array<{
		title?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		link?: Link
		_key: string
	}>
}

export type HelpCenterCategoriesList = {
	_type: 'help-center-categories-list'
	categories?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'help.center.category'
	}>
}

export type CategoriesList = {
	_type: 'categories-list'
	categories?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'blog.category'
	}>
}

export type HomeBriefGroup = {
	_type: 'home-brief-group'
	briefs?: Array<
		{
			_key: string
		} & Brief
	>
}

export type BriefGroup = {
	_type: 'brief-group'
	briefs?: Array<
		{
			_key: string
		} & Brief
	>
}

export type Brief = {
	_type: 'brief'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	onRight?: boolean
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		youtubeLink?: string
		loading?: 'lazy' | 'eager'
		_type: 'image'
	}
}

export type BlogRollup = {
	_type: 'blog-rollup'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	category?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'blog.category'
	}>
	layout?: 'grid' | 'carousel'
	limit?: number
}

export type List01 = {
	_type: 'list-01'
	features?: Array<{
		icon?: Icon
		title?: string
		description?: string
		_key: string
	}>
}

export type AppStoreRollup = {
	_type: 'app-store-rollup'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	apps?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'app.store.app'
	}>
	limit?: number
}

export type Applications = {
	_type: 'applications'
	pretitle?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	chips?: Array<{
		icon?: Icon
		image?: {
			asset?: {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
			}
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		title?: string
		description?: string
		link?: Link
		_key: string
	}>
	altAppsLogos?: Array<{
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
		_key: string
	}>
	comparisonTable?: Table
}

export type LinkGroup = {
	_type: 'link.group'
	label?: string
	links?: Array<
		{
			_key: string
		} & LinkList
	>
}

export type LinkList = {
	_type: 'link.list'
	label?: string
	links?: Array<
		{
			_key: string
		} & Link
	>
}

export type Cta = {
	_type: 'cta'
	link?: Link
	style?: 'primary' | 'secondary' | 'tertiary'
}

export type Faq = {
	_id: string
	_type: 'faq'
	_createdAt: string
	_updatedAt: string
	_rev: string
	language?: 'ar' | 'en'
	question?: string
	answer?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
}

export type Testimonial = {
	_id: string
	_type: 'testimonial'
	_createdAt: string
	_updatedAt: string
	_rev: string
	language?: 'ar' | 'en'
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	author?: {
		name?: string
		title?: string
		image?: {
			asset?: {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
			}
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
	}
}

export type PartnersLogos = {
	_id: string
	_type: 'partners.logos'
	_createdAt: string
	_updatedAt: string
	_rev: string
	name?: string
	icon?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
}

export type Logo = {
	_id: string
	_type: 'logo'
	_createdAt: string
	_updatedAt: string
	_rev: string
	name?: string
	icon?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
}

export type HelpCenterCategory = {
	_id: string
	_type: 'help.center.category'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	title_en?: string
}

export type HelpCenterPostEn = {
	_id: string
	_type: 'help.center.post.en'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: {
					_ref: string
					_type: 'reference'
					_weak?: boolean
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
				}
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				caption?: string
				_type: 'image'
				_key: string
		  }
	>
	categories?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'help.center.category'
	}>
	publishDate?: string
	metadata?: Metadata
}

export type HelpCenterPost = {
	_id: string
	_type: 'help.center.post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: {
					_ref: string
					_type: 'reference'
					_weak?: boolean
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
				}
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				caption?: string
				_type: 'image'
				_key: string
		  }
	>
	categories?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'help.center.category'
	}>
	publishDate?: string
	metadata?: Metadata
}

export type BlogCategory = {
	_id: string
	_type: 'blog.category'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: {
		ar?: string
		en?: string
	}
	slug?: Slug
}

export type BlogPostEn = {
	_id: string
	_type: 'blog.post.en'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: {
					_ref: string
					_type: 'reference'
					_weak?: boolean
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
				}
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				caption?: string
				_type: 'image'
				_key: string
		  }
	>
	categories?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'blog.category'
	}>
	callToAction?: {
		_ref: string
		_type: 'reference'
		_weak?: boolean
		[internalGroqTypeReferenceTo]?: 'call.to.action.doc'
	}
	publishDate?: string
	metadata?: Metadata
}

export type BlogPost = {
	_id: string
	_type: 'blog.post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: {
					_ref: string
					_type: 'reference'
					_weak?: boolean
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
				}
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				caption?: string
				_type: 'image'
				_key: string
		  }
	>
	categories?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'blog.category'
	}>
	callToAction?: {
		_ref: string
		_type: 'reference'
		_weak?: boolean
		[internalGroqTypeReferenceTo]?: 'call.to.action.doc'
	}
	publishDate?: string
	metadata?: Metadata
}

export type Redirect = {
	_id: string
	_type: 'redirect'
	_createdAt: string
	_updatedAt: string
	_rev: string
	source?: string
	destination?: string
	permanent?: boolean
}

export type Code = {
	_type: 'code'
	language?: string
	filename?: string
	code?: string
	highlightedLines?: Array<number>
}

export type TableRow = {
	_type: 'tableRow'
	cells?: Array<string>
}

export type InlineSvg = string

export type TranslationMetadata = {
	_id: string
	_type: 'translation.metadata'
	_createdAt: string
	_updatedAt: string
	_rev: string
	translations?: Array<
		{
			_key: string
		} & InternationalizedArrayReferenceValue
	>
	schemaTypes?: Array<string>
}

export type InternationalizedArrayReferenceValue = {
	_type: 'internationalizedArrayReferenceValue'
	value?:
		| {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'site'
		  }
		| {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'navigation'
		  }
		| {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'page'
		  }
		| {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'app.store.app'
		  }
		| {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'call.to.action.doc'
		  }
		| {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'pricing'
		  }
}

export type Pricing = {
	_id: string
	_type: 'pricing'
	_createdAt: string
	_updatedAt: string
	_rev: string
	language?: string
	title?: string
	highlight?: string
	apps?: Array<{
		title?: string
		icon?: Icon
		active?: boolean
		_type: 'app'
		_key: string
	}>
	displayPrice?: boolean
	price?: {
		monthly?: string
		yearly?: string
	}
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	features?: Array<{
		title?: string
		active?: boolean
		_type: 'feature'
		_key: string
	}>
}

export type CallToActionDoc = {
	_id: string
	_type: 'call.to.action.doc'
	_createdAt: string
	_updatedAt: string
	_rev: string
	language?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		onRight?: boolean
		loading?: 'lazy' | 'eager'
		_type: 'image'
	}
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	checkedList?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
}

export type AppStoreApp = {
	_id: string
	_type: 'app.store.app'
	_createdAt: string
	_updatedAt: string
	_rev: string
	language?: string
	title?: string
	description?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: {
					_ref: string
					_type: 'reference'
					_weak?: boolean
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
				}
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				caption?: string
				_type: 'image'
				_key: string
		  }
	>
	carousel?: Array<{
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		caption?: string
		_type: 'carousel-items'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	permissions?: {
		basicInfo?: boolean
		products?: boolean
		customers?: boolean
		orders?: boolean
		webhook?: boolean
	}
	icon?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	publishDate?: string
	metadata?: Metadata
}

export type Page = {
	_id: string
	_type: 'page'
	_createdAt: string
	_updatedAt: string
	_rev: string
	language?: string
	title?: string
	modules?: Array<
		| ({
				_key: string
		  } & Applications)
		| ({
				_key: string
		  } & AppStoreRollup)
		| ({
				_key: string
		  } & BlogRollup)
		| ({
				_key: string
		  } & Brief)
		| ({
				_key: string
		  } & BriefGroup)
		| ({
				_key: string
		  } & CallToAction01)
		| ({
				_key: string
		  } & CallToAction02)
		| ({
				_key: string
		  } & CategoriesList)
		| ({
				_key: string
		  } & ContactUs)
		| ({
				_key: string
		  } & CustomHtml)
		| ({
				_key: string
		  } & FaqList)
		| ({
				_key: string
		  } & Features01)
		| ({
				_key: string
		  } & Features02)
		| ({
				_key: string
		  } & HelpCenterCategoriesList)
		| ({
				_key: string
		  } & Hero01)
		| ({
				_key: string
		  } & Hero02)
		| ({
				_key: string
		  } & Hero03)
		| ({
				_key: string
		  } & Hero04)
		| ({
				_key: string
		  } & HomeBriefGroup)
		| ({
				_key: string
		  } & HowItWorks)
		| ({
				_key: string
		  } & List01)
		| ({
				_key: string
		  } & List02)
		| ({
				_key: string
		  } & Logos01)
		| ({
				_key: string
		  } & Logos02)
		| ({
				_key: string
		  } & PricingList)
		| ({
				_key: string
		  } & PricingCalculator)
		| ({
				_key: string
		  } & PricingComparison)
		| ({
				_key: string
		  } & ProductList)
		| ({
				_key: string
		  } & RichtextModule)
		| ({
				_key: string
		  } & StatList)
		| ({
				_key: string
		  } & Steps)
		| ({
				_key: string
		  } & Testimonials01)
		| ({
				_key: string
		  } & Testimonials02)
		| ({
				_key: string
		  } & JobApplicationTabs)
		| ({
				_key: string
		  } & Crm2)
		| ({
				_key: string
		  } & PromoBanner)
	>
	callToActionDoc?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'call.to.action.doc'
	}>
	metadata?: Metadata
}

export type Metadata = {
	_type: 'metadata'
	title?: string
	description?: string
	slug?: Slug
	image?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	noIndex?: boolean
	jsonLd?: Code
}

export type Table = {
	_type: 'table'
	rows?: Array<
		{
			_key: string
		} & TableRow
	>
}

export type Link = {
	_type: 'link'
	label?: string
	description?: string
	iconify?: Icon
	type?: 'internal' | 'external'
	internal?:
		| {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'page'
		  }
		| {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'blog.post'
		  }
	external?: string
	params?: string
}

export type Icon = {
	_type: 'icon'
	name?: string
}

export type Site = {
	_id: string
	_type: 'site'
	_createdAt: string
	_updatedAt: string
	_rev: string
	language?: string
	title?: string
	logo?: {
		name?: string
		icon?: {
			asset?: {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
			}
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		_type: 'logo'
	}
	callToActionDoc?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'call.to.action.doc'
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	headerMenu?: {
		_ref: string
		_type: 'reference'
		_weak?: boolean
		[internalGroqTypeReferenceTo]?: 'navigation'
	}
	footerMenu?: {
		_ref: string
		_type: 'reference'
		_weak?: boolean
		[internalGroqTypeReferenceTo]?: 'navigation'
	}
	social?: {
		_ref: string
		_type: 'reference'
		_weak?: boolean
		[internalGroqTypeReferenceTo]?: 'navigation'
	}
	staticLinks?: {
		_ref: string
		_type: 'reference'
		_weak?: boolean
		[internalGroqTypeReferenceTo]?: 'navigation'
	}
	ogimage?: {
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	gtmId?: string
}

export type Navigation = {
	_id: string
	_type: 'navigation'
	_createdAt: string
	_updatedAt: string
	_rev: string
	language?: string
	title?: string
	items?: Array<
		| ({
				_key: string
		  } & Link)
		| ({
				_key: string
		  } & LinkList)
		| ({
				_key: string
		  } & LinkGroup)
	>
}

export type InternationalizedArrayReference = Array<
	{
		_key: string
	} & InternationalizedArrayReferenceValue
>

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch'
	background?: string
	foreground?: string
	population?: number
	title?: string
}

export type SanityImagePalette = {
	_type: 'sanity.imagePalette'
	darkMuted?: SanityImagePaletteSwatch
	lightVibrant?: SanityImagePaletteSwatch
	darkVibrant?: SanityImagePaletteSwatch
	vibrant?: SanityImagePaletteSwatch
	dominant?: SanityImagePaletteSwatch
	lightMuted?: SanityImagePaletteSwatch
	muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions'
	height?: number
	width?: number
	aspectRatio?: number
}

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot'
	x?: number
	y?: number
	height?: number
	width?: number
}

export type SanityImageCrop = {
	_type: 'sanity.imageCrop'
	top?: number
	bottom?: number
	left?: number
	right?: number
}

export type SanityFileAsset = {
	_id: string
	_type: 'sanity.fileAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash?: string
	extension?: string
	mimeType?: string
	size?: number
	assetId?: string
	uploadId?: string
	path?: string
	url?: string
	source?: SanityAssetSourceData
}

export type SanityImageAsset = {
	_id: string
	_type: 'sanity.imageAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash?: string
	extension?: string
	mimeType?: string
	size?: number
	assetId?: string
	uploadId?: string
	path?: string
	url?: string
	metadata?: SanityImageMetadata
	source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata'
	location?: Geopoint
	dimensions?: SanityImageDimensions
	palette?: SanityImagePalette
	lqip?: string
	blurHash?: string
	hasAlpha?: boolean
	isOpaque?: boolean
}

export type Geopoint = {
	_type: 'geopoint'
	lat?: number
	lng?: number
	alt?: number
}

export type Slug = {
	_type: 'slug'
	current?: string
	source?: string
}

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData'
	name?: string
	id?: string
	url?: string
}

export type AllSanitySchemaTypes =
	| PromoBanner
	| Crm2
	| JobApplicationTabs
	| ProductList
	| Features02
	| Features01
	| List02
	| HowItWorks
	| Testimonials01
	| Testimonials02
	| Steps
	| CallToAction02
	| CallToAction01
	| StatList
	| Testimonials03
	| RichtextModule
	| PricingComparison
	| PricingCalculator
	| PricingList
	| Logos02
	| Logos01
	| Hero04
	| Hero02
	| Hero01
	| Hero03
	| FaqList
	| CustomHtml
	| CreativeModule
	| ContactUs
	| HelpCenterCategoriesList
	| CategoriesList
	| HomeBriefGroup
	| BriefGroup
	| Brief
	| BlogRollup
	| List01
	| AppStoreRollup
	| Applications
	| LinkGroup
	| LinkList
	| Cta
	| Faq
	| Testimonial
	| PartnersLogos
	| Logo
	| HelpCenterCategory
	| HelpCenterPostEn
	| HelpCenterPost
	| BlogCategory
	| BlogPostEn
	| BlogPost
	| Redirect
	| Code
	| TableRow
	| InlineSvg
	| TranslationMetadata
	| InternationalizedArrayReferenceValue
	| Pricing
	| CallToActionDoc
	| AppStoreApp
	| Page
	| Metadata
	| Table
	| Link
	| Icon
	| Site
	| Navigation
	| InternationalizedArrayReference
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityImageAsset
	| SanityImageMetadata
	| Geopoint
	| Slug
	| SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/app/sitemap.ts
// Variable: query
// Query: {		'pages': *[			_type == 'page' && 			(language == 'ar' || language == 'en') &&			!(metadata.slug.current in ['404']) &&			metadata.noIndex != true		] | order(metadata.slug.current) {			'url': $baseUrl + language + '/' + select(				metadata.slug.current == 'index' => '', 				metadata.slug.current			),			'lastModified': _updatedAt,			'slug': metadata.slug.current,			'priority': select(				metadata.slug.current == 'index' => 1,				0.5			),		},				'posts': *[			(_type == 'blog.post' || _type == 'blog.post.en') &&			metadata.noIndex != true		] | order(name) {			'url': $baseUrl + select(				_type == 'blog.post.en' => 'en/',				'ar/'			) + 'blog/' + metadata.slug.current,			'lastModified': _updatedAt,			'slug': metadata.slug.current,			'priority': 0.4,		},		'categories': *[			_type == 'blog.category' &&			metadata.noIndex != true		] | order(name) {			'url': $baseUrl + 'blog/category/' + slug.current,			'lastModified': _updatedAt,			'slug': slug.current,			'priority': 0.4,		},				'guides': *[			(_type == 'help.center.post' || _type == 'help.center.post.en') &&			metadata.noIndex != true		] | order(name) {			'url': $baseUrl + select(				_type == 'help.center.post.en' => 'en/',				'ar/'			) + 'help-center/' + metadata.slug.current,			'lastModified': _updatedAt,			'slug': metadata.slug.current,			'priority': 0.4,		},				'integrations': *[			_type == 'app.store.app' &&			metadata.noIndex != true		] | order(name) {			'url': $baseUrl + select(language == 'en' => 'en/', 'ar/') + 'integrations/' + metadata.slug.current,			'lastModified': _updatedAt,			'slug': metadata.slug.current,			'priority': 0.4,		}	}
export type QueryResult = {
	pages: Array<{
		url: unknown
		lastModified: string
		slug: string | null
		priority: 0.5 | 1
	}>
	posts: Array<{
		url: unknown
		lastModified: string
		slug: string | null
		priority: 0.4
	}>
	categories: Array<{
		url: unknown
		lastModified: string
		slug: string | null
		priority: 0.4
	}>
	guides: Array<{
		url: unknown
		lastModified: string
		slug: string | null
		priority: 0.4
	}>
	integrations: Array<{
		url: unknown
		lastModified: string
		slug: string | null
		priority: 0.4
	}>
}

// Source: ./src/sanity/lib/queries.ts
// Variable: creativeModuleQuery
// Query: modules[]{		...,		subModules[]{			...,			ctas[]{				...,				link{					...,					internal->{ title, metadata }				}			}		}	}
export type CreativeModuleQueryResult = never

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
	interface SanityQueries {
		"{\n\t\t'pages': *[\n\t\t\t_type == 'page' && \n\t\t\t(language == 'ar' || language == 'en') &&\n\t\t\t!(metadata.slug.current in ['404']) &&\n\t\t\tmetadata.noIndex != true\n\t\t] | order(metadata.slug.current) {\n\t\t\t'url': $baseUrl + language + '/' + select(\n\t\t\t\tmetadata.slug.current == 'index' => '', \n\t\t\t\tmetadata.slug.current\n\t\t\t),\n\t\t\t'lastModified': _updatedAt,\n\t\t\t'slug': metadata.slug.current,\n\t\t\t'priority': select(\n\t\t\t\tmetadata.slug.current == 'index' => 1,\n\t\t\t\t0.5\n\t\t\t),\n\t\t},\n\t\t\n\t\t'posts': *[\n\t\t\t(_type == 'blog.post' || _type == 'blog.post.en') &&\n\t\t\tmetadata.noIndex != true\n\t\t] | order(name) {\n\t\t\t'url': $baseUrl + select(\n\t\t\t\t_type == 'blog.post.en' => 'en/',\n\t\t\t\t'ar/'\n\t\t\t) + 'blog/' + metadata.slug.current,\n\t\t\t'lastModified': _updatedAt,\n\t\t\t'slug': metadata.slug.current,\n\t\t\t'priority': 0.4,\n\t\t},\n\n\t\t'categories': *[\n\t\t\t_type == 'blog.category' &&\n\t\t\tmetadata.noIndex != true\n\t\t] | order(name) {\n\t\t\t'url': $baseUrl + 'blog/category/' + slug.current,\n\t\t\t'lastModified': _updatedAt,\n\t\t\t'slug': slug.current,\n\t\t\t'priority': 0.4,\n\t\t},\n\t\t\n\t\t'guides': *[\n\t\t\t(_type == 'help.center.post' || _type == 'help.center.post.en') &&\n\t\t\tmetadata.noIndex != true\n\t\t] | order(name) {\n\t\t\t'url': $baseUrl + select(\n\t\t\t\t_type == 'help.center.post.en' => 'en/',\n\t\t\t\t'ar/'\n\t\t\t) + 'help-center/' + metadata.slug.current,\n\t\t\t'lastModified': _updatedAt,\n\t\t\t'slug': metadata.slug.current,\n\t\t\t'priority': 0.4,\n\t\t},\n\t\t\n\t\t'integrations': *[\n\t\t\t_type == 'app.store.app' &&\n\t\t\tmetadata.noIndex != true\n\t\t] | order(name) {\n\t\t\t'url': $baseUrl + select(language == 'en' => 'en/', 'ar/') + 'integrations/' + metadata.slug.current,\n\t\t\t'lastModified': _updatedAt,\n\t\t\t'slug': metadata.slug.current,\n\t\t\t'priority': 0.4,\n\t\t}\n\t}": QueryResult
		'\n\tmodules[]{\n\t\t...,\n\t\tsubModules[]{\n\t\t\t...,\n\t\t\tctas[]{\n\t\t\t\t...,\n\t\t\t\tlink{\n\t\t\t\t\t...,\n\t\t\t\t\tinternal->{ title, metadata }\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n': CreativeModuleQueryResult
	}
}
